Repository CGI-FR/IoT-Hub-Portal, pull requests merged in 2022-02, with the labels that each got.

#156 Add Working with the documentation info
  user-guide.md
Labels: documentation

#157 Rename user guide to dev guide
  _layouts/default.html
  dev-guide.md
Labels: documentation

#161 Display form error messages on CreateDeviceModel & DeviceModelDetail pages
  src/AzureIoTHub.Portal/Client/AzureIoTHub.Portal.Client.csproj
  src/AzureIoTHub.Portal/Client/Pages/DeviceModels/CreateDeviceModelPage.razor
  src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelDetailPage.razor
  src/AzureIoTHub.Portal/Shared/AzureIoTHub.Portal.Shared.csproj
  src/AzureIoTHub.Portal/Shared/Models/DeviceModel.cs
Labels: enhancement

#162 Change portaldeploy template
  src/AzureIoTHub.Portal.sln
  templates/portalDeploy.json
Labels: bug

#206 Add Unit tests for mappers
  src/AzureIoTHub.Portal.Server.Tests/Mappers/DeviceModelCommandMapperTests.cs
  src/AzureIoTHub.Portal.Server.Tests/Mappers/DeviceModelMapperTests.cs
  src/AzureIoTHub.Portal.Server.Tests/Mappers/DeviceTwinMapperTests.cs
  src/AzureIoTHub.Portal/Server/Extensions/StringExtension.cs
  src/AzureIoTHub.Portal/Server/Mappers/DeviceModelCommandMapper.cs
  src/AzureIoTHub.Portal/Server/Mappers/DeviceTwinMapper.cs
Labels: .NET

#267 Better comments on APIs documentation
  src/AzureIoTHub.Portal.Server.Tests/Controllers/ConcentratorsControllerTests.cs
  src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelControllerBase.cs
  src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelsController.cs
  src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesController.cs
  src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesControllerBase.cs
  src/AzureIoTHub.Portal/Server/Controllers/v1.0/EdgeConfigurationsController.cs
  src/AzureIoTHub.Portal/Server/Controllers/v1.0/EdgeDevicesController.cs
  src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANCommandsController.cs
  src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANConcentratorsController.cs
  src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANDeviceModelsController.cs
  src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANDevicesController.cs
  src/AzureIoTHub.Portal/Server/Controllers/v1.0/SettingsController.cs
  src/AzureIoTHub.Portal/Shared/AzureIoTHub.Portal.Shared.csproj
  src/AzureIoTHub.Portal/Shared/Models/v1.0/C2Dresult.cs
  src/AzureIoTHub.Portal/Shared/Models/v1.0/ConfigItem.cs
  src/AzureIoTHub.Portal/Shared/Models/v1.0/ConfigListItem.cs
  src/AzureIoTHub.Portal/Shared/Models/v1.0/Device/DeviceDetails.cs
  src/AzureIoTHub.Portal/Shared/Models/v1.0/DeviceModel/DeviceModel.cs
  src/AzureIoTHub.Portal/Shared/Models/v1.0/Gateway.cs
  src/AzureIoTHub.Portal/Shared/Models/v1.0/GatewayListItem.cs
  src/AzureIoTHub.Portal/Shared/Models/v1.0/GatewayModule.cs
  src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/Concentrator/Channel.cs
  src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/Concentrator/Concentrator.cs
  src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/Concentrator/RouterConfig.cs
  src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/LoRaDevice/Command.cs
  src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/LoRaDevice/LoRaDeviceDetails.cs
  src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/LoRaDeviceModel/LoRaDeviceModel.cs
  src/AzureIoTHub.Portal/Shared/Models/v1.0/RequestPayload.cs
  src/AzureIoTHub.Portal/Shared/Models/v1.0/SearchModel.cs
Labels: documentation
